### PR TITLE
Add SHA property

### PR DESCRIPTION
**Pull request by flcdrg**
Implements #191

### CODE REVIEW

**Comment by flcdrg** [comment]
@NasAmin is there an issue with the unit tests? I see other PRs are also failing with a similar error.

**Comment by NasAmin** [comment]
> @NasAmin is there an issue with the unit tests? I see other PRs are also failing with a similar error.

Hi @flcdrg Thanks for the PR. I'll look into the issue this evening (UK time). Could you please run `npm run all` locally and check in the files from the `dist` directory please? I should update the README to make that clearer.

**Comment by flcdrg** [comment]
No worries. I've regenerated the dist files from within WSL (previously I'd committed on Windows), so hopefully that fixes the line endings. I wonder if that could be related to the build failure?

**Comment by NasAmin** [comment]
No the failure seems to be due to an issue with the checks API and the permissions for the default GITHUB_TOKEN. I'll look into that later which will hopefully unblock  your PR.

**Comment by flcdrg** [comment]
Oh.. that sounds similar to what I've been dealing with in regards to dependabot PRs. GitHub now treats builds from forks differently. The GITHUB_TOKEN is readonly, so my build won't have permission to update the check.

It's a bit annoying. The workaround I ended up using was creating a separate workflow_run triggered workflow that ran after the original pr workflow. That workflow then runs with full access to a token. A bit of messing around though!

**Comment by NasAmin** [comment]
@flcdrg I have read through and it does seem like an issue on PRs from Forks. I'll fix this in due time but for now I don't see any problems with your PR. I'll approve and merge if you agree?

**Review by NasAmin — APPROVED** [review]

**Comment by flcdrg** [comment]
Sounds good to me!

**Pull request merged**
